validate:
  max_name: 50
  max_email: 255
  min_pass: 6
  max_content: 140
  max_address: 100
  max_phone: 15
  max_username: 50
  valid_email: !ruby/regexp '/\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i'
gravatar:
  size50: 50
  host: "http://gravatar.com/emails"
password_reset:
  time: 2
filed:
  min: 0
users_per_page: 10
savings_per_page: 5
zero: 0
status_income: "1"
status_expense: "0"
input_stats: "stats_year"
input_search: "search"
min_year: 1800
old_month_per_page: 5
this_month_per_page: 10
select_time_per_page: 10
page_index: 1
search1: "search1"
search2: "search2"
value_root: -1
id_tool_cat: "tool_cat"
id_modal: "modal"
expenditure_needed_percent: 50
savings: 10
education: 10
enjoy: 10
investment: 10
charity: 5
